# Generated by Django 3.2.5 on 2022-09-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_auto_20220908_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
    ]
