# Generated by Django 3.2.5 on 2022-09-12 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0004_auto_20220910_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='reated_date',
            new_name='created_date',
        ),
    ]
